import { Pause, Play, Square } from 'lucide-react';
import { memo, useRef } from 'react';
import { createPortal } from 'react-dom';

interface SimulatorControlsProps {
  state: {
    isPlaying: boolean;
  };
  currentBar: { time: number } | null;
  onPressPlayButton: () => void;
  onPressStart: () => void;
  onPressEnd: () => void;
  onStop: () => void;
}

const SimulatorControls = memo(({
  state,
  currentBar,
  onPressPlayButton,
  onPressStart,
  onPressEnd,
  onStop,
}: SimulatorControlsProps) => {
  const holdTimerRef = useRef<number | null>(null);
  const isLongPressRef = useRef(false);

  const formatTime = (ts: number | undefined) => {
    if (!ts) return "--/--/-- --:--:--";
    const d = new Date(ts);
    return d.toISOString().replace('T', ' ').substring(0, 19);
  };

  const clearHoldTimer = () => {
    if (holdTimerRef.current !== null) {
      window.clearTimeout(holdTimerRef.current);
      holdTimerRef.current = null;
    }
  };

  const handlePressStart = () => {
    clearHoldTimer();
    isLongPressRef.current = false;
    holdTimerRef.current = window.setTimeout(() => {
      isLongPressRef.current = true;
      onPressStart();
    }, 250);
  };

  const handlePressEnd = (event: React.PointerEvent<HTMLButtonElement>) => {
    const wasLongPress = isLongPressRef.current;
    clearHoldTimer();
    if (wasLongPress) {
      onPressEnd();
      // Stop the synthetic click generated by a long press release.
      event.preventDefault();
      isLongPressRef.current = false;
    }
  };

  const handleButtonClick = () => {
    if (isLongPressRef.current) {
      isLongPressRef.current = false;
      return;
    }
    onPressPlayButton();
  };

  const targetNode = document.getElementById('header-controls');

  const content = (
    <div className="flex items-center gap-4 bg-gray-100 px-3 py-1.5 rounded-lg border border-gray-200">
      <span className="font-mono text-sm font-bold text-gray-800 tabular-nums min-w-[150px] text-center">
        {formatTime(currentBar?.time)}
      </span>
      <div className="flex items-center gap-2 border-l border-gray-300 pl-4">
        <button
          onPointerDown={handlePressStart}
          onPointerUp={handlePressEnd}
          onPointerCancel={handlePressEnd}
          onPointerLeave={handlePressEnd}
          onClick={handleButtonClick}
          className="p-1.5 rounded-full hover:bg-gray-200 text-gray-700 bg-white shadow-sm border border-gray-200 transition-all"
          title="单击: 正常播放/暂停; 长按: 倍速播放, 松开暂停"
        >
          {state.isPlaying ? <Pause size={16} /> : <Play size={16} />}
        </button>

        <button onClick={onStop} className="p-1.5 rounded-full hover:bg-red-50 hover:text-red-600 hover:border-red-200 text-red-500 tooltip bg-white shadow-sm border border-gray-200 transition-all ml-1" title="结束并进行结算">
          <Square size={16} />
        </button>
      </div>
    </div>
  );

  return targetNode ? createPortal(content, targetNode) : null;
});

export default SimulatorControls;
